### PR TITLE
add support for pblog

### PR DESCRIPTION
**Pull request by andermi**
added to batching and standard launch

requires:
https://github.com/osrf/mbari_wec_utils/pull/44 <-- https://github.com/osrf/mbari_wec_utils/pull/47

### CODE REVIEW

**Comment by hamilton8415** [comment]
Looking good.  Could consider changing "latest_csv" to "latest" to match buoy behaviors.

**Comment by andermi** [comment]
> consider changing "latest_csv" to "latest"

I can do that, but I was hoping to distinguish between pblog and rosbag. No biggie if you'd like to have `latest` be pointing to the csv and perhaps `latest_rosbag` pointing to the rosbag

**Comment by hamilton8415** [comment]
I'm flexible.  Nothing automated relies on this and it's just a convenience so it can stay as is.

In general, I noticed a few things when I was running this yesterday (I was running from batch mode)
1) When the job started there was immediately a .gz version of the .csv file, even though the .csv file was still growing.  Same filename.
2) When it completed, the "latest" file pointed to the .gz file.  That is OK, but not really necessary.  For me anyway, I've been using the "latest" links as a quick way to see what's happening during a run (or a deployment).

**Comment by andermi** [comment]
1. Fixed
2. would you rather not gzip the log on exit? (only after a duration)

**Comment by hamilton8415** [comment]
Yeah, I think we should match the buoy, zip only at the end of an hour...

**Comment by andermi** [comment]
it was causing problems anyways... if it takes too long to gzip, the batch launch will SIGTERM/SIGKILL pblog before it finishes writing

**Comment by andermi** [comment]
@hamilton8415 ready for another check

**Comment by hamilton8415** [comment]
In testing this I realized the wave-seed wasn't getting passed along by IncidentWave.cpp.  Fixed this and pushed to this branch...

**Review by hamilton8415 — APPROVED** [review]
I have used this feature quite a bit in the last week or so and it's working very nicely.  The only changes here I might suggest is to rename the "latest_csv" symbolic link to "latest_csv_dir".  I kept thinking the link pointed at the latest .csv file...  But I got used to it.  Not a critical change.

The other hiccup I've found is maybe not due to this PR but rather the logging PR in _gz. When performing runs longer than one-hour, it zips the last file correctly, but there does seem to be a gap in results between the two files,  when running much faster than real-time the gap is greater than two minutes of sim time...  I will note this in the _gz pull request also.

**Comment by andermi** [comment]
> rename the "latest_csv" symbolic link to "latest_csv_dir"

changed in https://github.com/osrf/mbari_wec_utils/pull/44

**Comment by andermi** [comment]
> gap in results between the two files

fixed in osrf/mbari_wec_utils#44

**Comment by andermi** [comment]
@hamilton8415 can you try your matlab stuff against this latest patch to confirm the new IMU orientation?

**Comment by hamilton8415** [comment]
Lat/Lon working now.

**Pull request merged**
